version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: carbon_user
      POSTGRES_PASSWORD: carbon_pass
      POSTGRES_DB: carbon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: